# Full schema for application_train table
CREATE TABLE application_train (
    sk_id_curr BIGINT PRIMARY KEY,
    target SMALLINT NOT NULL,
    name_contract_type VARCHAR(100),
    code_gender VARCHAR(100),
    flag_own_car VARCHAR(100),
    flag_own_realty VARCHAR(100),
    cnt_children BIGINT,
    amt_income_total NUMERIC(14,3),
    amt_credit NUMERIC(14,3),
    amt_annuity NUMERIC(14,3),
    amt_goods_price NUMERIC(14,3),
    name_type_suite VARCHAR(100),
    name_income_type VARCHAR(100),
    name_education_type VARCHAR(100),
    name_family_status VARCHAR(100),
    name_housing_type VARCHAR(100),
    region_population_relative NUMERIC(14,3),
    days_birth BIGINT,
    days_employed BIGINT,
    days_registration NUMERIC(14,3),
    days_id_publish BIGINT,
    own_car_age NUMERIC(14,3),
    flag_mobil BIGINT,
    flag_emp_phone BIGINT,
    flag_work_phone BIGINT,
    flag_cont_mobile BIGINT,
    flag_phone BIGINT,
    flag_email BIGINT,
    occupation_type VARCHAR(100),
    cnt_fam_members NUMERIC(14,3),
    region_rating_client BIGINT,
    region_rating_client_w_city BIGINT,
    weekday_appr_process_start VARCHAR(100),
    hour_appr_process_start BIGINT,
    reg_region_not_live_region BIGINT,
    reg_region_not_work_region BIGINT,
    live_region_not_work_region BIGINT,
    reg_city_not_live_city BIGINT,
    reg_city_not_work_city BIGINT,
    live_city_not_work_city BIGINT,
    organization_type VARCHAR(100),
    ext_source_1 NUMERIC(14,3),
    ext_source_2 NUMERIC(14,3),
    ext_source_3 NUMERIC(14,3),
    apartments_avg NUMERIC(14,3),
    basementarea_avg NUMERIC(14,3),
    years_beginexpluatation_avg NUMERIC(14,3),
    years_build_avg NUMERIC(14,3),
    commonarea_avg NUMERIC(14,3),
    elevators_avg NUMERIC(14,3),
    entrances_avg NUMERIC(14,3),
    floorsmax_avg NUMERIC(14,3),
    floorsmin_avg NUMERIC(14,3),
    landarea_avg NUMERIC(14,3),
    livingapartments_avg NUMERIC(14,3),
    livingarea_avg NUMERIC(14,3),
    nonlivingapartments_avg NUMERIC(14,3),
    nonlivingarea_avg NUMERIC(14,3),
    apartments_mode NUMERIC(14,3),
    basementarea_mode NUMERIC(14,3),
    years_beginexpluatation_mode NUMERIC(14,3),
    years_build_mode NUMERIC(14,3),
    commonarea_mode NUMERIC(14,3),
    elevators_mode NUMERIC(14,3),
    entrances_mode NUMERIC(14,3),
    floorsmax_mode NUMERIC(14,3),
    floorsmin_mode NUMERIC(14,3),
    landarea_mode NUMERIC(14,3),
    livingapartments_mode NUMERIC(14,3),
    livingarea_mode NUMERIC(14,3),
    nonlivingapartments_mode NUMERIC(14,3),
    nonlivingarea_mode NUMERIC(14,3),
    apartments_medi NUMERIC(14,3),
    basementarea_medi NUMERIC(14,3),
    years_beginexpluatation_medi NUMERIC(14,3),
    years_build_medi NUMERIC(14,3),
    commonarea_medi NUMERIC(14,3),
    elevators_medi NUMERIC(14,3),
    entrances_medi NUMERIC(14,3),
    floorsmax_medi NUMERIC(14,3),
    floorsmin_medi NUMERIC(14,3),
    landarea_medi NUMERIC(14,3),
    livingapartments_medi NUMERIC(14,3),
    livingarea_medi NUMERIC(14,3),
    nonlivingapartments_medi NUMERIC(14,3),
    nonlivingarea_medi NUMERIC(14,3),
    fondkapremont_mode VARCHAR(100),
    housetype_mode VARCHAR(100),
    totalarea_mode NUMERIC(14,3),
    wallsmaterial_mode VARCHAR(100),
    emergencystate_mode VARCHAR(100),
    obs_30_cnt_social_circle NUMERIC(14,3),
    def_30_cnt_social_circle NUMERIC(14,3),
    obs_60_cnt_social_circle NUMERIC(14,3),
    def_60_cnt_social_circle NUMERIC(14,3),
    days_last_phone_change NUMERIC(14,3),
    flag_document_2 BIGINT,
    flag_document_3 BIGINT,
    flag_document_4 BIGINT,
    flag_document_5 BIGINT,
    flag_document_6 BIGINT,
    flag_document_7 BIGINT,
    flag_document_8 BIGINT,
    flag_document_9 BIGINT,
    flag_document_10 BIGINT,
    flag_document_11 BIGINT,
    flag_document_12 BIGINT,
    flag_document_13 BIGINT,
    flag_document_14 BIGINT,
    flag_document_15 BIGINT,
    flag_document_16 BIGINT,
    flag_document_17 BIGINT,
    flag_document_18 BIGINT,
    flag_document_19 BIGINT,
    flag_document_20 BIGINT,
    flag_document_21 BIGINT,
    amt_req_credit_bureau_hour NUMERIC(14,3),
    amt_req_credit_bureau_day NUMERIC(14,3),
    amt_req_credit_bureau_week NUMERIC(14,3),
    amt_req_credit_bureau_mon NUMERIC(14,3),
    amt_req_credit_bureau_qrt NUMERIC(14,3),
    amt_req_credit_bureau_year NUMERIC(14,3)
);

// Created a Staging Schema to store all staged tables here.

CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS clean;
CREATE SCHEMA IF NOT EXISTS features;

ALTER TABLE application_train
SET SCHEMA staging;

SELECT * FROM staging.application_train LIMIT 5;

SELECT COUNT(*) FROM staging.application_train;

